package_assets:         on                    # (on, off, always)
embed_assets:           on                    # (on, off, datauri)
compress_assets:        on                    # (on, off)
gzip_assets:            off                   # (on, off)
template_function:      _.template            # (defaults to the built-in micro-templating)
package_path:           ../assets     # (defaults to assets)
javascript_compressor:  closure               # (yui, closure)

javascripts:
  main:
      - assets/javascript/jquery.js
      - assets/javascript/fastclick.js
      - assets/javascript/soysauce.js