package_assets:         on                    # (on, off, always)
embed_assets:           on                    # (on, off, datauri)
compress_assets:        off                    # (on, off)
gzip_assets:            off                   # (on, off)
template_function:      _.template            # (defaults to the built-in micro-templating)
package_path:           javascript            # (defaults to assets)
javascript_compressor:  closure               # (yui, closure)

javascripts:
  carousel:
      - assets/javascript/soysauce/base.js
      - assets/javascript/soysauce/widgets/carousel.js
